version: '3.9'

services:
  web:
    image: python:3.13
    container_name: ai_interior_web
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    image: python:3.13
    container_name: ai_interior_celery
    command: >
      sh -c "pip install -r requirements.txt && celery -A AI_Interior worker --loglevel=info -P solo"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ai_interior_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  db:
    image: postgres:14
    container_name: ai_interior_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
